[package]
name = "verifier-api"
version = "0.1.0"
edition = "2024.beta"
authors = ["zkmove contributors"]

[addresses]
verifier_api = "0x0"
halo2_common = "0x0"

[dependencies]
Sui = { git = "https://github.com/zkmove/sui.git", rev = "76269b3f6ff1ea56ddfcf258be8c19ffe21ce105", subdir = "crates/sui-framework/packages/sui-framework" }
