[package]
name = "verifier_api"
edition = "2024.beta"
authors = ["zkmove contributors"]
implicit-dependencies = false

[dependencies]
std = { git = "https://github.com/zkmove/sui.git", rev = "76269b3f6ff1ea56ddfcf258be8c19ffe21ce105", subdir = "crates/sui-framework/packages/move-stdlib" }
sui = { git = "https://github.com/zkmove/sui.git", rev = "76269b3f6ff1ea56ddfcf258be8c19ffe21ce105", subdir = "crates/sui-framework/packages/sui-framework" }
