[package]
name = "vk-gen-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2.workspace = true
serde.workspace=true
serde_json.workspace=true
halo2_proofs.workspace=true
halo2_backend.workspace=true
hex.workspace=true
rand.workspace = true
rand_core.workspace=true
anyhow.workspace=true


#[patch."https://github.com/zkmove/halo2.git"]
#halo2_proofs = { path = "../../../halo2/halo2_proofs" }
#halo2_backend = { path = "../../../halo2/halo2_backend" }

#[patch."https://github.com/zkmove/halo2curves"]
#halo2curves = { path = "../../../halo2curves" }