[package]
name = "sui-verifier-api"
version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
edition.workspace = true

[dependencies]
halo2-verifier.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
halo2_proofs.workspace = true
halo2_backend.workspace = true
hex.workspace = true
anyhow.workspace = true
blake2b_simd.workspace = true
sui-ptb-helper.workspace = true
