[package]
name = "sui-verifier-api"
version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
halo2_proofs.workspace = true
halo2_backend.workspace = true
hex.workspace = true
anyhow.workspace = true
