#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

SUI_BIN="${SUI_BIN:-sui}"
SUI_CLIENT_CONFIG="${SUI_CLIENT_CONFIG:-}"
VERIFIER_API_PACKAGE="${VERIFIER_API_PACKAGE:-}"
VERIFY_DIR="${VERIFY_DIR:-${ROOT_DIR}/txns/sui-verify}"
VERIFY_TXN="${VERIFY_TXN:-}"
OUT_DIR="${OUT_DIR:-${ROOT_DIR}/txns/sui-proof-upload}"
ENV_FILE="${ENV_FILE:-}"
GAS_BUDGET="${GAS_BUDGET:-1000000000}"
CHUNK_SIZE="${CHUNK_SIZE:-15360}"

log() {
  printf '[upload-sui-proof] %s\n' "$*" >&2
}

die() {
  printf '[upload-sui-proof] ERROR: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Upload a Sui verifier proof from a generated zkmove verify descriptor.

Inputs:
  --verify-txn <file>
      Explicit verify descriptor generated by:
        zkmove sui build-verify-proof-native-txn
      Defaults to the only *-verify-proof-native.txn under --verify-dir.

  --verify-dir <dir>
      Directory containing one *-verify-proof-native.txn descriptor.
      Default: $VERIFY_DIR or <halo2-verifier.move>/txns/sui-verify

Options:
  --verifier-api-package <package-id>
      Published verifier_api package id. If omitted, the script reads the
      package field from the generated verify descriptor.

  --out-dir <dir>
      Directory for proof-builder transaction JSON outputs.
      Default: $OUT_DIR or <halo2-verifier.move>/txns/sui-proof-upload

  --env-file <file>
      File that receives exported variables for the final verify call.
      Default: $ENV_FILE or <out-dir>/sui-proof-builder.env

  --sui-bin <path>
      Sui CLI binary. Default: $SUI_BIN or sui.

  --client-config <file>
      Optional Sui client config file. Also supported via SUI_CLIENT_CONFIG.

  --gas-budget <mist>
      Gas budget for every Sui call. Default: 1000000000.

  --chunk-size <bytes>
      Upload chunk size for byte-array pure arguments. Default: 15360.

Example:
  scripts/upload_sui_proof.sh \
    --verifier-api-package "$VERIFIER_API_PACKAGE" \
    --verify-txn txns/sui-verify/test_fibonacci-1778483369682-verify-proof-native.txn \
    --out-dir txns/sui-proof-upload

  source txns/sui-proof-upload/sui-proof-builder.env
EOF
}

arg_value() {
  [[ $# -ge 2 ]] || die "$1 requires a value"
  [[ -n "$2" && "$2" != --* ]] || die "$1 requires a value"
  printf '%s\n' "$2"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verify-txn)
      VERIFY_TXN="$(arg_value "$@")"
      shift 2
      ;;
    --verify-dir)
      VERIFY_DIR="$(arg_value "$@")"
      shift 2
      ;;
    --verifier-api-package)
      VERIFIER_API_PACKAGE="$(arg_value "$@")"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="$(arg_value "$@")"
      shift 2
      ;;
    --env-file)
      ENV_FILE="$(arg_value "$@")"
      shift 2
      ;;
    --sui-bin)
      SUI_BIN="$(arg_value "$@")"
      shift 2
      ;;
    --client-config)
      SUI_CLIENT_CONFIG="$(arg_value "$@")"
      shift 2
      ;;
    --gas-budget)
      GAS_BUDGET="$(arg_value "$@")"
      shift 2
      ;;
    --chunk-size)
      CHUNK_SIZE="$(arg_value "$@")"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

ENV_FILE="${ENV_FILE:-${OUT_DIR}/sui-proof-builder.env}"

require_bin() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

resolve_single_file() {
  local dir="$1"
  local name_pattern="$2"
  local label="$3"
  local matches=()
  local candidate

  while IFS= read -r -d '' candidate; do
    matches+=("${candidate}")
  done < <(find "${dir}" -maxdepth 1 -type f -name "${name_pattern}" -print0)

  if [[ "${#matches[@]}" -eq 0 ]]; then
    die "could not find ${label}; expected ${dir}/${name_pattern}"
  fi
  if [[ "${#matches[@]}" -gt 1 ]]; then
    printf '[upload-sui-proof] Multiple %s candidates found:\n' "${label}" >&2
    printf '  %s\n' "${matches[@]}" >&2
    die "pass --${label}-txn explicitly"
  fi

  printf '%s\n' "${matches[0]}"
}

json_arg_compact() {
  jq -c --argjson index "$2" '
    if (.args | type) != "array" or (.args | length) <= $index then
      error("missing args[" + ($index | tostring) + "]")
    else
      .args[$index]
    end
  ' "$1"
}

json_arg_string() {
  jq -r --argjson index "$2" '
    if (.args | type) != "array" or (.args | length) <= $index then
      error("missing args[" + ($index | tostring) + "]")
    else
      .args[$index]
    end
  ' "$1"
}

json_package() {
  jq -r '.package // empty' "$1"
}

json_byte_arg_digest() {
  python3 - "$1" "$2" <<'PY'
import hashlib
import json
import sys

path = sys.argv[1]
index = int(sys.argv[2])
with open(path, "r", encoding="utf-8") as f:
    payload = json.load(f)

args = payload.get("args")
if not isinstance(args, list) or index >= len(args):
    raise SystemExit(f"{path}: missing args[{index}]")

values = args[index]
if not isinstance(values, list):
    raise SystemExit(f"{path}: args[{index}] is not a byte array")

out = bytearray()
for i, value in enumerate(values):
    if not isinstance(value, int) or value < 0 or value > 255:
        raise SystemExit(f"{path}: args[{index}][{i}] is not a byte")
    out.append(value)

digest = hashlib.blake2b(bytes(out), digest_size=32).digest()
print("[" + ",".join(str(b) for b in digest) + "]")
PY
}

json_byte_arg_len() {
  python3 - "$1" "$2" <<'PY'
import json
import sys

path = sys.argv[1]
index = int(sys.argv[2])
with open(path, "r", encoding="utf-8") as f:
    payload = json.load(f)

args = payload.get("args")
if not isinstance(args, list) or index >= len(args):
    raise SystemExit(f"{path}: missing args[{index}]")

values = args[index]
if not isinstance(values, list):
    raise SystemExit(f"{path}: args[{index}] is not a byte array")

for i, value in enumerate(values):
    if not isinstance(value, int) or value < 0 or value > 255:
        raise SystemExit(f"{path}: args[{index}][{i}] is not a byte")

print(len(values))
PY
}

json_byte_arg_chunks() {
  python3 - "$1" "$2" "$3" <<'PY'
import json
import sys

path = sys.argv[1]
index = int(sys.argv[2])
chunk_size = int(sys.argv[3])
if chunk_size <= 0:
    raise SystemExit("chunk size must be positive")

with open(path, "r", encoding="utf-8") as f:
    payload = json.load(f)

args = payload.get("args")
if not isinstance(args, list) or index >= len(args):
    raise SystemExit(f"{path}: missing args[{index}]")

values = args[index]
if not isinstance(values, list):
    raise SystemExit(f"{path}: args[{index}] is not a byte array")

data = bytearray()
for i, value in enumerate(values):
    if not isinstance(value, int) or value < 0 or value > 255:
        raise SystemExit(f"{path}: args[{index}][{i}] is not a byte")
    data.append(value)

for offset in range(0, len(data), chunk_size):
    chunk = data[offset:offset + chunk_size]
    print("[" + ",".join(str(b) for b in chunk) + "]")
PY
}

tx_succeeded() {
  jq -e '
    (.effects.status.status? == "success")
    or (.effects.status? == "success")
  ' >/dev/null
}

created_object_id() {
  local suffix="$1"
  jq -r --arg suffix "${suffix}" '
    first(
      .objectChanges[]?
      | select(.type == "created")
      | select((.objectType // "") | endswith($suffix))
      | .objectId
    ) // empty
  '
}

check_tx_json() {
  local label="$1"
  local out="$2"

  if ! jq empty "${out}" >/dev/null 2>&1; then
    log "${label} did not return JSON; full output follows"
    cat "${out}" >&2
    exit 1
  fi
  if ! tx_succeeded <"${out}"; then
    log "${label} failed; full JSON follows"
    cat "${out}" >&2
    exit 1
  fi
}

sui_client_json() {
  if [[ -n "${SUI_CLIENT_CONFIG}" ]]; then
    "${SUI_BIN}" client --client.config "${SUI_CLIENT_CONFIG}" --json -q "$@"
  else
    "${SUI_BIN}" client --json -q "$@"
  fi
}

call_json() {
  local out="$1"
  local package="$2"
  local module="$3"
  local function="$4"
  shift 4

  sui_client_json call \
    --package "${package}" \
    --module "${module}" \
    --function "${function}" \
    --gas-budget "${GAS_BUDGET}" \
    "$@" >"${out}"
  check_tx_json "${module}::${function}" "${out}"
}

shell_export() {
  local name="$1"
  local value="$2"
  printf "export %s='" "${name}"
  printf '%s' "${value}" | sed "s/'/'\\\\''/g"
  printf "'\n"
}

main() {
  require_bin jq
  require_bin python3
  require_bin find
  [[ "${CHUNK_SIZE}" =~ ^[0-9]+$ ]] || die "chunk size must be an integer"
  [[ "${GAS_BUDGET}" =~ ^[0-9]+$ ]] || die "gas budget must be an integer"

  if [[ "${SUI_BIN}" == */* ]]; then
    [[ -x "${SUI_BIN}" ]] || die "Sui binary not found or not executable: ${SUI_BIN}"
  else
    require_bin "${SUI_BIN}"
  fi

  if [[ -z "${VERIFY_TXN}" ]]; then
    [[ -d "${VERIFY_DIR}" ]] || die "verify dir not found: ${VERIFY_DIR}"
    VERIFY_TXN="$(resolve_single_file "${VERIFY_DIR}" '*-verify-proof-native.txn' verify)"
  fi
  [[ -f "${VERIFY_TXN}" ]] || die "verify txn not found: ${VERIFY_TXN}"

  if [[ -z "${VERIFIER_API_PACKAGE}" ]]; then
    VERIFIER_API_PACKAGE="$(json_package "${VERIFY_TXN}")"
  fi
  [[ -n "${VERIFIER_API_PACKAGE}" ]] || die "missing --verifier-api-package and verify descriptor has no package field"

  mkdir -p "${OUT_DIR}" "$(dirname "${ENV_FILE}")"

  local params_object_id vk_object_id public_inputs_json proof_digest
  local kzg_variant k_present k_value proof_len
  params_object_id="$(json_arg_string "${VERIFY_TXN}" 0)"
  vk_object_id="$(json_arg_string "${VERIFY_TXN}" 1)"
  public_inputs_json="$(json_arg_compact "${VERIFY_TXN}" 2)"
  proof_digest="$(json_byte_arg_digest "${VERIFY_TXN}" 3)"
  kzg_variant="$(json_arg_string "${VERIFY_TXN}" 4)"
  k_present="$(json_arg_string "${VERIFY_TXN}" 5)"
  k_value="$(json_arg_string "${VERIFY_TXN}" 6)"
  proof_len="$(json_byte_arg_len "${VERIFY_TXN}" 3)"
  [[ "${proof_len}" -gt 0 ]] || die "proof byte array is empty"

  log "Verify descriptor: ${VERIFY_TXN}"
  log "Verifier API package: ${VERIFIER_API_PACKAGE}"
  log "Params object: ${params_object_id}"
  log "VK object: ${vk_object_id}"
  log "Proof bytes: ${proof_len}"
  log "KZG variant: ${kzg_variant}; k_present: ${k_present}; k: ${k_value}"

  local builder_out proof_builder
  builder_out="${OUT_DIR}/proof.builder.json"
  log "Creating proof builder"
  call_json "${builder_out}" "${VERIFIER_API_PACKAGE}" artifact_builder publish_proof_builder
  proof_builder="$(created_object_id "::artifact_builder::ArtifactBuilder" <"${builder_out}")"
  [[ -n "${proof_builder}" ]] || die "could not parse proof builder object id from ${builder_out}"

  local idx=0
  local chunk_json
  while IFS= read -r chunk_json; do
    [[ -n "${chunk_json}" ]] || continue
    idx=$((idx + 1))
    local out="${OUT_DIR}/proof.append.${idx}.json"
    log "Appending proof chunk ${idx}"
    call_json "${out}" "${VERIFIER_API_PACKAGE}" artifact_builder append_chunk \
      --args "${proof_builder}" "${chunk_json}"
  done < <(json_byte_arg_chunks "${VERIFY_TXN}" 3 "${CHUNK_SIZE}")
  [[ "${idx}" -gt 0 ]] || die "proof artifact is empty"

  {
    shell_export VERIFY_TXN "${VERIFY_TXN}"
    shell_export VERIFIER_API_PACKAGE "${VERIFIER_API_PACKAGE}"
    shell_export PARAMS_OBJECT_ID "${params_object_id}"
    shell_export VK_OBJECT_ID "${vk_object_id}"
    shell_export PROOF_BUILDER "${proof_builder}"
    shell_export PROOF_DIGEST "${proof_digest}"
    shell_export PUBLIC_INPUTS_JSON "${public_inputs_json}"
    shell_export KZG_VARIANT "${kzg_variant}"
    shell_export K_PRESENT "${k_present}"
    shell_export K_VALUE "${k_value}"
  } >"${ENV_FILE}"

  log "Proof builder object: ${proof_builder}"
  log "Wrote env file: ${ENV_FILE}"
  printf 'PROOF_BUILDER=%s\n' "${proof_builder}"
  printf 'PROOF_DIGEST=%s\n' "${proof_digest}"
}

main "$@"
